apiVersion: apps/v1
kind: Deployment
metadata:
  name: irssi-mosh
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irssi-mosh
  template:
    metadata:
      labels:
        app: irssi-mosh
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-ssh
          image: busybox
          command: ['sh', '-c', 'mkdir -p /etc/ssh && chown 1000:1000 /etc/ssh']
          volumeMounts:
            - mountPath: /etc/ssh
              name: ssh-keys
          securityContext:
            runAsUser: 0
      imagePullSecrets:
        - name: ghcr-io-cred
      containers:
        - name: irssi-mosh
          image: ghcr.io/mfreeman451/irc-k8s:v0.0.7
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
            - name: mosh-start
              containerPort: 60000
              protocol: UDP
            - name: mosh-end
              containerPort: 61000
              protocol: UDP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /home/m/.irssi
              name: irssi-config
            - mountPath: /etc/ssh
              name: ssh-keys
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: irssi-config
          persistentVolumeClaim:
            claimName: irssi-config-pvc
        - name: ssh-keys
          persistentVolumeClaim:
            claimName: ssh-keys-pvc