apiVersion: apps/v1
kind: Deployment
metadata:
  name: irssi-mosh
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irssi-mosh
  template:
    metadata:
      labels:
        app: irssi-mosh
    spec:
      imagePullSecrets:
        - name: ghcr-io-cred
      containers:
        - name: irssi-mosh
          image: ghcr.io/mfreeman451/irc-k8s:v0.0.33
          imagePullPolicy: Always
          ports:
            - containerPort: 22
              protocol: TCP
            - name: mosh-start
              containerPort: 60000
              protocol: UDP
            - name: mosh-end
              containerPort: 61000
              protocol: UDP
          volumeMounts:
            - name: ssh-config
              mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
            - name: ssh-config
              mountPath: /home/m/.ssh/authorized_keys
              subPath: authorized_keys
            - name: irssi-config
              mountPath: /home/m/.irssi
          securityContext:
            privileged: true
      volumes:
        - name: ssh-config
          configMap:
            name: ssh-config
            defaultMode: 0600
        - name: irssi-config
          persistentVolumeClaim:
            claimName: irssi-config-pvc