apiVersion: apps/v1
kind: Deployment
metadata:
  name: irssi-mosh
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irssi-mosh
  template:
    metadata:
      labels:
        app: irssi-mosh
    spec:
      imagePullSecrets:
        - name: ghcr-io-cred
      initContainers:
        - name: init-ssh
          image: debian:bullseye
          command:
            - sh
            - -c
            - |
              mkdir -p /home/m/.ssh
              cp /config/authorized_keys /home/m/.ssh/
              chown -R 1000:1000 /home/m
              chmod 700 /home/m/.ssh
              chmod 600 /home/m/.ssh/authorized_keys
          volumeMounts:
            - name: home
              mountPath: /home/m
            - name: ssh-config
              mountPath: /config
      containers:
        - name: irssi-mosh
          image: ghcr.io/mfreeman451/irc-k8s:v0.0.38
          imagePullPolicy: Always
          ports:
            - containerPort: 22
              protocol: TCP
            - name: mosh-start
              containerPort: 60000
              protocol: UDP
            - name: mosh-end
              containerPort: 61000
              protocol: UDP
          volumeMounts:
            - name: ssh-config
              mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
            - name: home
              mountPath: /home/m
            - name: irssi-config
              mountPath: /home/m/.irssi
          securityContext:
            privileged: true
      volumes:
        - name: ssh-config
          configMap:
            name: ssh-config
            defaultMode: 0600
        - name: home
          emptyDir: {}
        - name: irssi-config
          persistentVolumeClaim:
            claimName: irssi-config-pvc