apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: default
data:
  sshd_config: |
    Port 22
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    UsePAM no
    PubkeyAuthentication yes
    AuthorizedKeysFile .ssh/authorized_keys
    AllowUsers m
    StrictModes no
    LogLevel DEBUG3
    AddressFamily any
    ListenAddress 0.0.0.0
    ListenAddress ::
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA2FW4CO+W1RQR4uIbEdzmXQSltWJl+fMgvs9WWfvrTq m@slowburnin.net