apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: default
data:
  sshd_config: |
    Port 22
    AddressFamily any
    ListenAddress 0.0.0.0
    ListenAddress ::
    Protocol 2
    HostKey /etc/ssh/ssh_host_rsa_key
    HostKey /etc/ssh/ssh_host_ecdsa_key
    HostKey /etc/ssh/ssh_host_ed25519_key
    PermitRootLogin no
    PubkeyAuthentication yes
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    UsePAM no
    X11Forwarding no
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem sftp /usr/lib/openssh/sftp-server
    AllowUsers m
    StrictModes no
    AuthorizedKeysFile .ssh/authorized_keys
    LogLevel DEBUG3
  authorized_keys: |-
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA2FW4CO+W1RQR4uIbEdzmXQSltWJl+fMgvs9WWfvrTq m@slowburnin.net
