apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: default
data:
  sshd_config: |
    Port 22
    AddressFamily any
    ListenAddress 0.0.0.0
    ListenAddress ::
    PermitRootLogin no
    PubkeyAuthentication yes
    PasswordAuthentication yes
    ChallengeResponseAuthentication no
    UsePAM yes
    X11Forwarding no
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem sftp /usr/lib/openssh/sftp-server
    AllowUsers m
    StrictModes no
    LogLevel DEBUG3
    AuthorizedKeysFile .ssh/authorized_keys

    # Unlock password auth temporarily for debugging
    PermitUserEnvironment yes
    UsePAM yes
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA2FW4CO+W1RQR4uIbEdzmXQSltWJl+fMgvs9WWfvrTq m@slowburnin.net